apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
    containers:
    - name: database
      image: wdennington/database:latest
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database
            key: MYSQL_ROOT_PASSWORD       