pipeline {
    agent any
    stages {
        stage('setup') {
            steps {
                sh "bash setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "echo 'skipping.....'"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash deploy.sh"
            }
        }
    }
}